### ISSUE TITLE
class not found issue

### ISSUE THREAD

**Issue by lalitarya128** [rhysnhall/etsy-php-sdk#11]
Class 'Etsy\Utils\PermissionScopes' not found when call getAuthorizationUrl() function from OAuth/client.php. plaese given me any sugeestion

**Comment by rhysnhall** [comment]
How did you install the package and how are you calling the getAuthorizationUrl() method?
Can you provide some code?

**Comment by lalitarya128** [comment]
I have download this sdk pakage.
        $etsy         = new Etsy\Etsy($api_key, $secret_key);
        $etsy_client    = new Etsy\OAuth\Client($api_key);

        $challangecode = $etsy_client->generateChallengeCode();
        $nonce = $etsy_client->createNonce();
        error_log(var_export($challangecode[1],true));
        error_log(" nonce code ::- ".$nonce);
        $scope = array('email_r', 'listings_r', 'listings_w' ,'transactions_r');
        $redirect_uri = _SERVER_.'index.php?p=etsy_process;
        $request_token = $etsy_client->getAuthorizationUrl($redirect_uri, $scope ,$challangecode[1], $nonce);

**Comment by rhysnhall** [comment]
Are you autoloading the package?

**Comment by lalitarya128** [comment]
I have downloaded the source code (zip) from asset

**Comment by rhysnhall** [comment]
You need to be autoloading the package. Unfortunately, this is an issue with your setup and I am unable to help.

**Comment by lalitarya128** [comment]
Hello Sir
I am trying to Authenticate with 2.0 Oauth with the below URL but I am getting an error massage.
An error occurred
The requested redirect URL is not permitted.

what should I do?
https://www.etsy.com/oauth/connect/?response_type=code&redirect_uri=https://lalit-sh/index.php?p=etsy_credentials_process&sid=232&seller_id=3764&scope=email_r%20listings_r%20listings_w%20transactions_r&client_id=sv6otbnwtdg0rwjiblzrkrj&state=2460a56cfe02e2bf9c492e95&code_challenge=yKgCKrBmHfOWURYSMLxGyzkVEz7DghEEJMHt5d-CHypM&code_challenge_method=S256

Please help what should I do now

**Comment by rhysnhall** [comment]
Hey @lalitarya128 ,
Check out the Etsy dev guide on OAuth2 and the [redirect URI section here](https://developers.etsy.com/documentation/essentials/authentication/#redirect-uris). You need to ensure that the URI has been registered with your app.

You also have query params in your redirect URI. This is most likely causing issues too. I would suggest not using these and changing your app to support this.

Change:
```
redirect_uri=https://lalit-sh/index.php?p=etsy_credentials_process&sid=232&seller_id=3764
```
To:
```
redirect_uri=https://lalit-sh/index.php
```
