### ISSUE TITLE
ListingProperty->update() has no effect

### ISSUE THREAD

**Issue by quape** [rhysnhall/etsy-php-sdk#14]
This API is awesome, I'm using it to implement all v3 stuff. Everything works so far except updating listing properties.

Since `$listing->getListingProperty()` is not working yet I'm using `$listing->getListingProperties()` to return all properties and for one specific I do this:

```
$prop->update(array(
  "value_ids" => array(743),
  "values" => array('Sewing'),
  "scale_id" => 10 // meters
));
```

Thats returns the old data and also has no effect on the properties. Any ideas?

**Comment by rhysnhall** [comment]
I'll test this out and come back to you.

**Comment by rhysnhall** [comment]
Okay, the endpoint for updating properties has changed. I have been slack in keeping up with updates, as I have a newer version of this SDK to release.
I'll review all endpoints for changes and push an update to the current version tonight that will fix this.
Also, I still can't believe they have not released the endpoint for the getListingProperty yet.

**Comment by rhysnhall** [comment]
The  #latest version resolves this.

**Comment by quape** [comment]
It now works like a charm, man! Thanks!
