### ISSUE TITLE
Enable pagination support for Receipts

### ISSUE THREAD

**Issue by guerrillacontra** [rhysnhall/etsy-php-sdk#15]
It should be supported based on the official docs (offset+limit)

https://developers.etsy.com/documentation/reference#operation/getShopReceipts

But in Collection we have:

  const PAGINATION_SUPPORT = [
    "Shop", "Review", "Listing"
  ];
  
  Which prevents me from being able to pull in more than 100 orders without writing my own paginator.

  $receipts = $shop->getReceipts([
            'limit'=>y,
            'offset'=>y
        ]);

**Comment by rhysnhall** [comment]
Thanks for bringing this up @guerrillacontra 
At the time of writing, the API did not support this. Good to see they have added it. 
I have fallen behind on keeping up to date with their changes. I have also reviewed and added pagination support for Transactions and LedgerEntry.

Patch incoming.
