### ISSUE TITLE
How to send shipping back to Etsy?

### ISSUE THREAD

**Issue by mgwalk** [rhysnhall/etsy-php-sdk#25]
Hi #rhysnhall
Can you show me how to update the shipping on the Receipt?  

I get Receipts
`
$etsy = new Etsy\Etsy($api_key, $oauthtoken);

$etsy->getShopReceipts(...)
`

**Comment by rhysnhall** [comment]
Apologies on the delayed response. This repo is now being maintained again. A major updated for the package has been released that will impact this issue. If this is something you still need assistance with, please open a new issue.
