### ISSUE TITLE
Problem with 'PATCH' method

### ISSUE THREAD

**Issue by abubakrelzoghby** [rhysnhall/etsy-php-sdk#26]
The new updateListing API "https://developers.etsy.com/documentation/reference/#operation/updateListing"
The method should be 'PATCH'.

But when I tried to run $listing->update() it doesn't work, the request succeeded but the data didn't change.

I found in the client file 'OAuth/Client.php'
In the `__call` method
In line `109`
'patch' method doesn't exist in the `in_array` check.

I added 'patch' method in the array and it works fine.

Thanks.

**Comment by ELY3M** [comment]
you need to do pull request.

**Comment by rhysnhall** [comment]
Apologies on the delayed response. An updated version of the package is available that addresses this.
