### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Etsy\Etsy\OAuth\Client' not found 

### ISSUE THREAD

**Issue by anzgar01** [rhysnhall/etsy-php-sdk#30]
Hi there,

for some reason, my script fails at 
$client = new Etsy\OAuth\Client($api_key);

with the following error:
Fatal error: Uncaught Error: Class 'Etsy\Etsy\OAuth\Client' not found 

what could be the problem? I am using the code from the readme file.
The Errors states "Etsy\Etsy", which might be the cause, but how do I change that?

I added the following, because I thought it might be missing, but that didn't help:
require_once __DIR__ . '/vendor/autoload.php';

Anyone got a clue what I might be doing wrong?
Thanks in advance!

**Comment by rhysnhall** [comment]
@anzgar01 Add a backslash before $client = new Etsy\OAuth\Client($api_key);

```php
$client = new \Etsy\OAuth\Client($api_key);
```

When importing a namespace you do not need a backslash. So this works:

```php
use Etsy\OAuth\Client;

$client = new Client($api_key);
```

But if the namespace has not been imported, you must use an absolute identifier. You do this by adding the backslash, which defines the absolute path.

```php
$client = new Etsy\OAuth\Client($api_key);

// If this script exists in a folder called Etsy then it look for the class starting at that point, as in: Etsy\Etsy\OAuth\Client
```
