### ISSUE TITLE
Invalid Token on getInventory()

### ISSUE THREAD

**Issue by keyurshah** [rhysnhall/etsy-php-sdk#4]
Hello,

Thank you for this great library.

I am trying to get the Inventory details for a listing

My code is as follows:

```php
$listing_id = '9999';
$api_key = 'xxx';
$access_token = 'yyy';


$etsy = new Etsy($api_key, $access_token);
$test = $etsy->getListing($listing->id); 
//dd($test); //this works when showing the results from getListing

dd($test->getInventory()) //this does not work
```

when trying to do `$test->getInventory()` I get the following error. But the token works in the prior `$etsy->getListing()` request.

Wondering if I am doing something wrong or if the getInventory method is not setting the access token properly.

Thanks.

```
  Received HTTP status code [401] with error "invalid_token".

  at D:\myfiles\laragon\www\alloy\vendor\rhysnhall\etsy-php-sdk\src\OAuth\Client.php:109
    105▕         $response->error = "{$body->error}";
    106▕         $response->code = $status_code;
    107▕         return $response;
    108▕       }
  ➜ 109▕       throw new RequestException(
    110▕         "Received HTTP status code [$status_code] with error \"{$body->error}\"."
    111▕       );
    112▕     }
    113▕   }

  1   D:\myfiles\laragon\www\alloy\vendor\rhysnhall\etsy-php-sdk\src\Resource.php:185
      Etsy\OAuth\Client::__call("get")
```

**Comment by rhysnhall** [comment]
Sounds like missing permission scopes.
When you authorized your app, did you request the *listings_r* scope? If you are unsure, best to re-authorize and ensure the permission scope is added.
This one is required for the getInventory() method, whereas no scope is required for the getListing() method.

**Comment by keyurshah** [comment]
Thanks for the quick response! I redid it and that seems to have made it work. Thanks for your time and help.

**Comment by keyurshah** [comment]
I think it turns out that it was an expired token. I'll look into implementing your code for using the refresh token.
